[package]
name = "mdbook-tera"
version = "0.2.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"
description = "Tera preprocessor for mdBook"
documentation = "https://github.com/avitex/mdbook-tera"
homepage = "https://github.com/avitex/mdbook-tera"
repository = "https://github.com/avitex/mdbook-tera"
license = "MIT"

[dependencies]
clap = "~2"
tera = "^1.3.1"
toml = "~0.5"
mdbook = "0.3"
serde = "~1"
serde_json = "~1"
globwalk = "0.8"
thiserror = "1.0"
semver = "0.10"