[package]
name = "mdbook-tera"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2"
tera = "~1"
toml = "~0.5"
mdbook = "~0.3"
serde = "~1"
serde_json = "~1"
error-chain = "~0.12"
semver = "0.9"